loki:
  enabled: true

promtail:
  enabled: true

grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30008

prometheus:
  enabled: true
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 0Gi