loki:
  enabled: true

promtail:
  enabled: true

grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30008

prometheus:
  enabled: true
  service:
    type: NodePort
    nodePort: 30007