---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |-
    {
      "extends": ["config:best-practices"],
      "repositories": [
          "ackamma/renovate-bot-test",
      ],
      "packageRules": [
          {
              "groupName": "NPM Packages",
              "matchDatasources": [
                  "npm"
              ],
          },
          {
              "groupName": "RUBY Packages",
              "matchDatasources": [
                  "rubygems"
              ],
          },
          {
              "groupName": "PYTHON Packages",
              "matchDatasources": [
                  "pypi"
              ],
          }
      ],
      "docker-compose": {
          "enabled": false
      },
      "lockFileMaintenance": { "enabled": true },  
      "hostRules": [{
          "matchHost": "http://172.17.0.3:8081/",
          "username": "admin",
          "password": process.env.NEXUS_PASSWORD,
      }],
      "npmrc": "registry=registry.npmjs.org/", 
      "npmrcMerge": true,
      "customEnvVariables": { 
          "BUNDLE_172__17__0__3" : process.env.BUNDLE_172__17__0__3
      },
      "fetchChangeLogs": "off",
      "prHourlyLimit": 0

    }

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
spec:
  schedule: '*/3 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: ghcr.io/mend/renovate-ce:11.0.0-full 
              name: renovate-bot
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: MEND_RNV_REQUEST_LOGGER_ENABLED
                  value: "true"
              envFrom:
                - secretRef:
                    name: renovate-env
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}