apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - chart: argo-cd
      repoURL: 'https://argoproj.github.io/argo-helm'
      targetRevision: 8.3.0
      helm:
        valueFiles:
          - $values/values/argocd-values.yaml
    - repoURL: 'https://github.com/ackammawork/zcloud-gitops/'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

