apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 76.4.0
      helm:
        valueFiles:
          - $values/values/prometheus-values.yaml
    - repoURL: 'https://github.com/ackammawork/zcloud-gitops/'
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true

